### ISSUE TITLE
Excellent article，

### ISSUE THREAD

**Issue by TrustTheBoy** [spencercarli/getting-started-react-navigation#1]
[https://hackernoon.com/getting-started-with-react-navigation-the-navigation-solution-for-react-native-ea3f4bd786a4](url)
Can I translate the article into Chinese? Share it with other partners through the social platform, and of course I will add my original address

**Comment by spencercarli** [comment]
Yeah that would be great as long is it links back to the original. Let me know when it's completed so I can add a link to it!
