### ISSUE TITLE
Double Header showing on StackNavigator nested in TabNavigator

### ISSUE THREAD

**Issue by omar-faruk-sust** [spencercarli/getting-started-react-navigation#12]
Hello, I have followed your nice tutorial, it's working fine but i am facing an issue with header. It's showing double header. Can you tell how can i fix this issue please? 
<img width="705" alt="screen shot 2018-04-03 at 8 51 48 pm" src="https://user-images.githubusercontent.com/7138045/38283007-71be55a0-3781-11e8-9ca1-5ab5bd685ac8.png">

<img width="365" alt="screen shot 2018-04-03 at 8 53 19 pm" src="https://user-images.githubusercontent.com/7138045/38282954-198a82a0-3781-11e8-8350-ec26be0c55d9.png">

but if i add this param ({ headerMode: 'none' } )in stackNavigator it works but in my event details page the back button disappears

**Comment by spencercarli** [comment]
You want to hide the header of the navigator at the very top of the stack of navs, like I do [here](https://github.com/spencercarli/getting-started-react-navigation/blob/master/app/config/router.js#L60). You're probably adding it to your EventsStack, which would hide the back button.
