### ISSUE TITLE
what are the navigationsoptions

### ISSUE THREAD

**Issue by TechSnake** [spencercarli/getting-started-react-navigation#3]
I watched your video about react navigaiton it s so clear to understand because the documentation of react navigations ,as i understand , is not easy.

I have a question to you I hope dont bother you .where can i find full feature of navigationoptions .I have just learnt 2 of them title and so on but there must be many . I checked the documentaions of  react navigations but nothing 

Thank you in Advance

**Comment by spencercarli** [comment]
It depends on the navigation you're using

- [StackNavigator](https://reactnavigation.org/docs/navigators/stack#Screen-Navigation-Options)
- [TabNavigator](https://reactnavigation.org/docs/navigators/tab#Screen-Navigation-Options)
- [DrawerNavigator](https://reactnavigation.org/docs/navigators/drawer#Screen-Navigation-Options)
