### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by virtueteam** [spencercarli/getting-started-react-navigation#4]
How to run it? 

# Running

- `react-native run-ios`
- `react-native run-androi

installation works just fine though, please advice.

**Comment by spencercarli** [comment]
Do you see a warning when using `react-native run-ios`? If you're trying `react-native run-android` make sure you've got a device connected or your android emulator running already

**Comment by ricbermo** [comment]
Hi, I took some time to create an Expo version of this. Here's the repo https://github.com/ricbermo/getting-started-react-navigation-expo

**Comment by spencercarli** [comment]
@ricbermo nice! I'm going to add a link this to the README - that okay with you?

**Comment by ricbermo** [comment]
@spencercarli yeah, it's Ok

**Comment by nandesu** [comment]
@virtueteam  
For iOS the project directory name must be the same as the AppRegistry name in index.ios.js.
So rename the main directory and then execute: 

- mv getting-started-react-navigation FirstLookReactNavigation
- cd FirstLookReactNavigation 
- react-native run-ios

**Comment by getcreativ** [comment]
when I try to run react-native run-ios,

my terminal says,
-bash: react-native: command not found

I assumed that installation was fine and additionally I did rename the main directory name that above

**Comment by spencercarli** [comment]
Fixed via d8f2d0e7d5f56918dfbd5de7df20d9779c9f5fe1
