### ISSUE TITLE
Unable to run this Project

### ISSUE THREAD

**Issue by nitinsindhubt** [spencercarli/getting-started-react-navigation#5]
I am Unable to run this App  on ios Device , it is showing error "Unable to resolve 'prop-types' from node_modules/react-native-navigation/src/View/sharedElementTrasition.ios.js': Module not found "

Please tell me how i can run this project in  ios Simulator .
??

![simulator screen shot 09-oct-2017 3 50 04 pm](https://user-images.githubusercontent.com/30141402/31334052-17b09d18-ad0a-11e7-9aa2-b55544562cad.png)

**Comment by spencercarli** [comment]
You'll need to add prop-types (`npm install --save prop-types`) and then import and `import { PropTypes } from 'React';` with `import PropTypes from 'prop-types';` throughout the project.

I would accept a pr for this change

**Comment by spencercarli** [comment]
Fixed via d8f2d0e7d5f56918dfbd5de7df20d9779c9f5fe1
