### ISSUE TITLE
Errors while running project

### ISSUE THREAD

**Issue by Dantalion** [spencercarli/getting-started-react-navigation#6]
While running the project in Android Emulator I am getting multiple errors.

When starting the error
`_reactNative.Dimensions.addEventListener is not a function`
is thrown.

Every time I press any Button the error 
`Cannot read property 'getScrollableNode' of undefined`
is thrown.
![error_nav](https://user-images.githubusercontent.com/10487018/31892631-d2ff22a6-b809-11e7-82ce-ef19f4c84386.PNG)

The only thing that works correctly is dragging the views from _feed_ and _me_ back and forth.

**Comment by Mate38** [comment]
The exact same error here

**Comment by Crasheng** [comment]
Hii did u got a solution?

**Comment by assurancetourix** [comment]
I got the error _reactNative.Dimensions.addEventListener is not a function

I have fixed with the following steps

- remove the node_modules folder

- update package.json with

>   "dependencies": {
>     "react": "16.0.0-alpha.6",
>     "react-native": "0.43.0",
>     "react-native-elements": "0.14.0",
>     "react-native-vector-icons": "4.4.2",
>     "react-navigation": "^1.0.0-beta.6"
>   },

- npm install

**Comment by spencercarli** [comment]
FIxed via d8f2d0e7d5f56918dfbd5de7df20d9779c9f5fe1
