### ISSUE TITLE
Error when run project

### ISSUE THREAD

**Issue by LinhLK** [spencercarli/getting-started-react-navigation#7]
Hi guy, 
I have a problem when run your project, please tell me about to fix it,
 thank you!
![error](https://user-images.githubusercontent.com/33614232/32709345-40629626-c862-11e7-838f-05bd42a55f8d.png)

**Comment by spencercarli** [comment]
What version of React Native are you using?

**Comment by spencercarli** [comment]
Fixed via d8f2d0e7d5f56918dfbd5de7df20d9779c9f5fe1
