### ISSUE TITLE
error _reactNative.Dimensions.addEventListener is not a function

### ISSUE THREAD

**Issue by assurancetourix** [spencercarli/getting-started-react-navigation#8]
I got the error _reactNative.Dimensions.addEventListener is not a function

I have fixed with the following steps

- remove the node_modules folder

- update package.json with

>     "dependencies": {
>     "react": "16.0.0-alpha.6",
>     "react-native": "0.43.0",
>     "react-native-elements": "0.14.0",
>     "react-native-vector-icons": "4.4.2",
>     "react-navigation": "^1.0.0-beta.6"
>     },

- npm install

**Comment by spencercarli** [comment]
Fixed via d8f2d0e7d5f56918dfbd5de7df20d9779c9f5fe1
